tools:
    php_cs_fixer: true
    php_code_sniffer:
        config:
            standard: Generic
    php_mess_detector: true
    php_analyzer:
        filter:
            excluded_paths: ["*/Tests/*"]
    sensiolabs_security_checker: true
