language: php

php:
  - 5.4

env:
  global:
    - SAUCE_USERNAME=myplanet-skeletor
    # SAUCE_ACCESS_KEY
    - secure: "FegBL7IVCVSvOBg0rGwUqL+Lci9kT9xLI/yDMOqjE1J4C9cpSSzhz9pEe/w0\n1GHgGZOkPYwRHl28qGqxvF6oOoiX3dLS1xO39c89GPNwY1GPuCF6Sv3ySAm4\nD86FRhxuJmSDkYfucIYVMwmTWxNY+DoSDnBtnbPLSFXFCh+cXCM="
  matrix:
    - DRUSH_VERSION=5.8.0

before_install: tmp/scripts/travis_before_install.sh

before_script:
  - tmp/scripts/travis_install.sh
  - curl https://gist.github.com/patcon/5164034/raw/e2a090e6ea639a0d700e6d02cee048fa2f6c8617/sauce_connect_setup.sh | bash

script: tmp/scripts/travis_test.sh
